server:
  port: 8080

openai:
  url: https://api.openai.com/v1/chat/completions
  key: ${SPRING_AI_OPENAI_API_KEY}
  model: gpt-4o
  config:
    max-tokens: 1512
    temperature: 1

spring:
  temporal:
    namespace: cv-analyzer-stage
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: org.blueliner.springbootwithkotlin
  ai:
    openai:
      chat:
        api-key: ${SPRING_AI_OPENAI_API_KEY}
        options:
          temperature: 1
          model: gpt-4o-mini
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 1500
        multiplier: 2
      on-client-errors: false # use retry even status is 4xx. Don't use it because of the request limit policy